### ISSUE TITLE
ENH [mrsix]: terminal-based image viewer using sixel

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#2079]
Displaying images on a remote server is very difficult / impossible currently using `mrview`, due the incompatibility of OpenGL 3+ with X11 forwarding ([see here for details](https://community.mrtrix.org/t/remote-display-issues/2547)). It will be some time before the technology is updated to fix this. 

In the meantime, it should be possible to allow some (limited) display functionality using [sixel](https://en.wikipedia.org/wiki/Sixel). The [libsixel project](https://saitoha.github.io/libsixel/) provides an implementation that seems like a good starting point. 

### Tasks

- [ ] extract a given slice of interest and render it to the terminal using [libsixel](https://saitoha.github.io/libsixel/)
- [ ] implement options or other user controls to select the slice of interest, projection (axial/sagittal/coronal), and brightness/control
- [ ] understand how to capture keyboard input and use this to control the slice of interest in real time
- [ ] understand how to capture mouse events and use this to further interact with the display

#### Optional

- [ ] add crosshairs and a status bar to report position and voxel intensity
- [ ] allow control of the colourmap
- [ ] build in the use of overlays (all images limited to the same grid)

**Comment by maxpietsch** [comment]
I'd add an optional task to support image display via other custom escape sequences such as
- [ ] iTerm2 (macOS) image inlining as this works directly without the need to install libsixel on the server (also supported by `niicat`).  [documentation](https://www.iterm2.com/documentation-images.html), [example command](https://www.iterm2.com/utilities/imgcat). For Linux, [terminology](https://www.enlightenment.org/about-terminology.md) seems to support similar  [escapes](https://manpages.debian.org/unstable/terminology-data/terminology.1.en.html) functionality.
