### ISSUE TITLE
dwidenoise enhancements list

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#3023]
There have been multiple potential enhancements to `dwidenoise` discussed. While there may be additional ideas for improving denoising that may be kept private as research developments, this list is items that are hopefully acceptable for public listing for the purpose of participant recruitment.

- [ ] Evaluate demeaning: #2363
    Use of single-precision floating-point with an imprecise decomposition algorithm can lead to artifacts in noise estimation & rank selection. One potential solution proposed some time ago was to explicitly demean the signal, storing that mean as a signal component to be included in the output series. Doing so however necessitates ensuring that the rank estimation does not become biased.
 
- [ ] Alternative decomposition: #2906
    Simply changing the decomposition used from the Eigen library may improve precision, though at the cost of computation time. This should ideally be evaluated across multiple use cases.

- [ ] Modify rank estimation: #2591
    May be possible to directly translate the modified estimators from externally published work to the *MRtrix3* implementation. Would need to contrast against the existing modification of @jelleveraart's estimator as "`Exp2`".

- [ ] Facilitate two-pass approach: #2274
    This could be used to stabilise against outliers in noise level estimation. It could also be used in pipelines that explicitly separate between the estimation of corrections to be applied vs. the application of those corrections.

- [ ] Spherical kernel: #2742
    Already published; having implemented would reduce issues around kernel size selection, and could also be used to mitigate against issues of kernel size / independence at FoV extremities.

- [ ] Handle >4D data: #3021
    Would make the method more amenable in particular to multi-echo fMRI data.

- [ ] Soft component thresholding: #3022
    Would mitigate quantisation effects due to a component being just above vs. just below the MP distribution cutoff. May improve denoising of datasets with a very small number of volumes.

Also:

- [ ] Build dataset of exemplar series for denoising efficacy evaluation
    Sometimes we hear about a particular dataset where the denoising performs poorly. We're also now using this method for multi-echo fMRI data in addition to DWI data. So it would be good to start building a dataset of different acquisitions of different quality, so that methods and heuristics can be refined to try to make the implementation robust against such variation, or to provide instructions on recommended settings in different scenarios.
